### ISSUE TITLE
credentails are not working

### ISSUE THREAD

**Issue by yameenyasin** [cloudmu/react-redux-starter-kit#14]
tried with user:admin and password:password. But they dont seem to work.

![image](https://cloud.githubusercontent.com/assets/6688507/18180926/a2124bec-70a6-11e6-8e05-c0cc97dd9de3.png)

**Comment by cloudmu** [comment]
Odd. It works for me.  Are you using the deployed demo, or under dev mode?
Make sure the admin/password are in lowercase.  In dev mode, make sure you are runnig the API server too.

**Comment by yameenyasin** [comment]
Sorry my bad. I missed to run the API Server.
Thank you so much for pointing this out.
