### ISSUE TITLE
Refactor react container files?

### ISSUE THREAD

**Issue by richb-hanover** [cloudmu/react-redux-starter-kit#15]
To make the containers more "portable", perhaps you could consider changing the organization of the various files for a particular container. It could change from:

```
actions
   foo.js
reducers
   foo.js
containers
   foo
      Foo.js
      foo.css
```

to

```
containers
   foo
      Foo.js
      foo.css
      actions.js
      reducers.js
```

This keeps all the Foo-related files in the same folder. I could duplicate the `foo` folder to create a new `bar` container. It also tidies up the file list in the IDE - only a couple folders need to be expanded. Thanks.

**Comment by cloudmu** [comment]
The starter kit doesn't intend to mandate the folder structure.  You should feel free to use a folder structure that works best for your project.   With that said, the current folder structure does make sense.  It helps with testing (actions/reducers) without involving browser.  It's a common folder structure. See [redux samples](https://github.com/reactjs/redux/tree/master/examples/real-world/src).

Others suggested the so called [ducks](https://github.com/erikras/ducks-modular-redux)

In my real project, I adopt yet another folder structure which groups files by domain. See [link](http://marmelab.com/blog/2015/12/17/react-directory-structure.html).

**Comment by richb-hanover** [comment]
Yes, I had seen the "ducks" article. +1 on your link to the Marmelab's blog posting for a [Better File Structure For React/Redux Applications](http://marmelab.com/blog/2015/12/17/react-directory-structure.html) Thanks!
