### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by LouisLoode** [cloudmu/react-redux-starter-kit#16]
Hi,
I did all the steps to run your starter on localhost but i have a blank page as you can see.
Can you help me ?

![capture d ecran 2016-09-14 a 23 39 36](https://cloud.githubusercontent.com/assets/5059708/18531152/1560175e-7ad5-11e6-8b9d-7bbfeb022a69.png)

Thank you for your establishment

**Comment by cloudmu** [comment]
I just downloaded the repo and tested under Win10 and OS X.  It worked just fine.

I am getting the same command line output and chrome dev console logs, just like yours.  But I also get the home page showing as expected in chrome. 

What you got is quite odd.  It never happened before.   It's hard to speculate without error messages in the chrome dev console.  Could you try to open `localhost:3000` in Firefox or Safari?

**Comment by LouisLoode** [comment]
First, thanks for your reactivity :)
Okay i tested the boilerplate with Safari, the home is again blank page, i go to http://localhost:3000/#/login and i have the sign in form. (Didn't work with Chrome) 
The signin action didn't work
![capture d ecran 2016-09-15 a 19 50 35](https://cloud.githubusercontent.com/assets/5059708/18560893/c8f900f2-7b7d-11e6-829f-58ece2caab93.png)

On Firefox i had more informations, it seems to come from the websockets. (Don't know why we have these informations just with firefox)
![capture d ecran 2016-09-15 a 19 53 42](https://cloud.githubusercontent.com/assets/5059708/18560996/4b880b1c-7b7e-11e6-8531-e237b74f0e76.png)

I try to fix it with globally installing socket.io but didn't fix the problem.

**Comment by cloudmu** [comment]
I don't think you need to globally install socket.io.  It doesn't seem to be the reason from the console log.

I am afraid there is something else going on.  What's your node and npm versions?  Could you do a clean download in a new folder and do the npm install, and npm start again?  No need to even start the server yet.

**Comment by LouisLoode** [comment]
Okay it was my bad, I read wrong node and npm version requierment. My past node config:
![capture d ecran 2016-09-15 a 20 08 56](https://cloud.githubusercontent.com/assets/5059708/18561886/f847a1c0-7b81-11e6-817e-02717f12c10f.png)

My new config:
![capture d ecran 2016-09-15 a 20 21 48](https://cloud.githubusercontent.com/assets/5059708/18561907/112aaffc-7b82-11e6-832a-8bf768b8674c.png)

Thanks for your help everythings works fine ;) (you save me a lot of time)
