### ISSUE TITLE
Bootstrap, jquery replacement with React -bootstrap (+ React-router-bootstrap optionally)

### ISSUE THREAD

**Issue by rsingh25** [cloudmu/react-redux-starter-kit#18]
Thank you for this excelled starter kit. 

There seems to be some downside of using bootstrap with react. 
References: 
http://stackoverflow.com/questions/38122652/advantages-of-using-react-bootstrap-over-bootstrap#answer-38136836
http://stackoverflow.com/questions/38015494/can-we-use-pure-bootstrap-with-react-js#answer-38017636

What is the recommended approach to replace bootstrap, jquery with react-bootstrap? Is React -bootstrap inclusion there on the road map for this kit?

Thanks again.

**Comment by rsingh25** [comment]
Is this why the project ignores to import 'bootstrap.js' in [index.js](https://github.com/cloudmu/react-redux-starter-kit/blob/master/src/index.js)?

**Comment by cloudmu** [comment]
There is trade-off between using 'raw' bootstrap and using react-bootstrap as the wrapper.  react-bootstrap would introduce another dependency, and an extra layer on top of bootstrap. Also a wrapper would always be behind (e.g. bootstrap 4.0)

With that said you should be able to find plenty of examples on react-bootstrap if you want to use it.  You can import react-bootstrap following create-react-app section [#adding-bootstrap](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-bootstrap).

 You may also want to look into alternatives such as [aphrodite](https://github.com/Khan/aphrodite), and [Elemental UI](http://elemental-ui.com/), etc.

**Comment by cloudmu** [comment]
Note there is another bootstrap wrapper you may find interesting:
[reactstrap](https://reactstrap.github.io/)

**Comment by rsingh25** [comment]
Thank you for your response.
