### ISSUE TITLE
How to Set Access-Control-Allow-Origin Headers

### ISSUE THREAD

**Issue by darrindickey** [cloudmu/react-redux-starter-kit#19]
I'm trying to make an API call to an external endpoint using the ApiUtils file, however I'm getting CORS errors while running the app on localhost. If I use mode: "no-cors" as the config, then I get an opaque response, which shows as a failure and I get no data in the browser. In both cases, I can see in my Inspect Element/Networks tab that the API call is completing and JSON response is being returned to the browser

I tried using the CORS middleware from expressjs, but it doesn't seem to do any good.

How can I add CORS headers to my calls?

**Comment by cloudmu** [comment]
API call relies on create-react-app feature: [Proxying API Requests in Development](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development).

Alternatively, you can [Enable CORS](http://enable-cors.org/server_expressjs.html), using Express as example.

**Comment by darrindickey** [comment]
@cloudmu Thanks. I gave both a try, but still can't call the DarkSky api without CORS errors. Perhaps I implemented them incorrectly.

**Comment by cloudmu** [comment]
I finally got a chance to look into it. The CORS issue with DarkSky is really not this starter-kit specific.  While investigating it I ended up implementing a solution that accesses Dark Sky API through an API proxy server. It not only solves the CORS issue, but also hides the Dark Sky API key.  You may want to take a look at the [darksky](https://github.com/cloudmu/darksky) project I just checked in.

**Comment by cloudmu** [comment]
@darrindickey since darksky server is not CORS enabled, you have two options:  
- use a proxy server. See my example [darksky](https://github.com/cloudmu/darksky)
- or use `jsonp`.  You may want to try [fetch-jsonp](https://github.com/camsong/fetch-jsonp), which has a API similar to that of `fetch`.

Again, I recommend proxy server approach.  Hope this answers your question.

**Comment by darrindickey** [comment]
@cloudmu Thanks for your reply and your proposed solutions. An update to my computer killed my laptop and I spent the last day rebuilding from scratch.  I'll check out your solutions as soon as everything is back up and running.
