### ISSUE TITLE
Dealing with missing modules

### ISSUE THREAD

**Issue by matmoi** [cloudmu/react-redux-starter-kit#21]
after a fresh install, I got missing "Module no found" errors for both 'tether' and 'history'.
I dealt with it in a quick/dirty way (I guess) by adding their full reference to index.js:
diff --git a/src/index.js b/src/index.js
index e164c4b..6aa9359 100644
--- a/src/index.js
+++ b/src/index.js
@@ -5,7 +5,7 @@ import 'bootstrap/dist/css/bootstrap.css';
 import 'font-awesome/css/font-awesome.css';
 import jquery from 'jquery';
 window.$ = window.jQuery=jquery;
-window.Tether=require('tether');
+window.Tether=require('bootstrap/node_modules/tether/dist/js/tether');
 require('bootstrap/dist/js/bootstrap');
 /////////////////////////////////////////////

@@ -20,7 +20,7 @@ import { Router, Route, IndexRoute} from 'react-router';
 // Please change to browserHistory if you have your own backend server.
 // import {browserHistory as history} from 'react-router';
 import { useRouterHistory } from 'react-router';
-import { createHashHistory } from 'history'
+import { createHashHistory } from 'react-router/node_modules/history';
 const history = useRouterHistory(createHashHistory)();

I don't know why/if I'm the only one reporting this problem (something might be wrong with my setup). An other way to solve it would be to include tether and history modules in package.json dependencies.

**Comment by cloudmu** [comment]
What's your npm version?  Node >= 6 and npm >= 3 are recommended. see [README](https://github.com/cloudmu/react-redux-starter-kit#getting-started).
npm3 would install dependencies in a [flat way](https://docs.npmjs.com/how-npm-works/npm3#npm-v3-dependency-resolution).

You may also want to delete node_modules and do a fresh `npm install`.

**Comment by matmoi** [comment]
you're absolutely right, an old version of npm 1.\* was hiding in my environment. Thanks for the fast feedback !
