### ISSUE TITLE
WebSocket Errors

### ISSUE THREAD

**Issue by darrindickey** [cloudmu/react-redux-starter-kit#23]
Has anyone else reported getting this error?
websocket.js:100 
WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket&sid=1d7ohKBWl6zb_HfvAAC7' 
failed: Connection closed before receiving a handshake response

It pops up about 30 - 60 seconds after my api calls run and has been happening since I originally started using the react-redux-starter-kit.

**Comment by cloudmu** [comment]
This project doesn't use websocket.  It uses socketio instead,  to show server notifications, which has been working fine.  

It's hard to help/comment without a test case. Have you resolved your issue?  If not, can you create a github project that people can duplicate the issue?
