### ISSUE TITLE
How does one push from an action?

### ISSUE THREAD

**Issue by mikepc** [cloudmu/react-redux-starter-kit#24]
I am new to react and I'm using this amazing boilerplate for a new project. I'm having trouble figuring out how exactly I can push the state from within a dispatched action. There is only one place where a redirect happens and that is in the restricted component. I don't see any other redirects.

I would post to SO, but this is pretty specific to this starter kit and I hoped maybe I could get some help from here?

Thank you very much in advance!

**Comment by cloudmu** [comment]
I don't think I follow what you exactly mean by the following:

> how exactly I can push the state from within a dispatched action

State management (including dispatching action etc) is not this project specific. This project uses [Redux](http://redux.js.org/) for state management.  Redux has the best documentation/tutorials on [dispatching action and data flow](http://redux.js.org/docs/basics/DataFlow.html)

However, [Redux is NOT necessary for React](http://redux.js.org/docs/faq/General.html#general-when-to-use), especially if you are new to React. I would recommend getting comfortable with React first.  The official React documentation is a great place to [get started](https://facebook.github.io/react/docs/hello-world.html).

Hope this helps.
