### ISSUE TITLE
Changes required for Bootstrap 4.0.0-alpha.6?

### ISSUE THREAD

**Issue by richb-hanover** [cloudmu/react-redux-starter-kit#25]
I forked your project many months ago, and have happily developing from that base. Thanks!

My GUI got seriously disturbed when I updated to Bootstrap 4.0.0-alpha.6. I see that you made a series of changes on 8 Jan 2017 that coincide with the update. 

Do you have a summary of what you changed (or a pointer to what guided you)? Thanks again!

**Comment by cloudmu** [comment]
I don't have a summary, but the three areas of changes you may look into:
1.  nav navbar related changes
2.  pager
3.  panel  (use card in v4 instead)

Also check out the [v4-alpha6 blog](http://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/).

**Comment by richb-hanover** [comment]
Thanks. Since I hadn't made many interesting changes to Header.js, I just copied your newest over, and made my changes again. Worked fine. (I did find the  v4-alpha6 blog, which made me think more about the Header.js...)
