### ISSUE TITLE
Support for any CSS Preprocessors

### ISSUE THREAD

**Issue by gitlovenotwar** [cloudmu/react-redux-starter-kit#6]
Please add to support any CSS preprocessors.

**Comment by bhtabor** [comment]
This project is now based on [create-react-app](https://github.com/facebookincubator/create-react-app) and create-react-app doesn't currently support any CSS pre-processors. https://github.com/facebookincubator/create-react-app/blob/master/template/README.md#post-process-css

**Comment by cloudmu** [comment]
@BirukHaileye Thanks.  I will close this for now.  Hopefully create-react-app will supports CSS  pre-processors at some point.
